### PR TITLE
Copper support

### PR DESCRIPTION
**Pull request by CubeGame**
This pull request brings copper support (#3)

Other changes include version detection for 1.17, prefixed names for mechanization with `m` and to the README, which will need to be altered when merged.

### CODE REVIEW

**Comment by TheWii** [comment]
Greetings. I appreciate this pull request a lot, thank you for the effort! I'm going to review the changes you made and also update some things as well.

**Comment by Dethkiller15** [comment]
I updated it to 1.17 ores but I haven't touched mechanization.

https://github.com/Dethkiller15/auto-utilities-vein-mining

**Comment by TheWii** [comment]
Hello Dethkiller15, sorry for the late answer. I'm looking at your changes and I swear I'm gonna add them this time XD

**Comment by TheWii** [comment]
Closing this pull request because all these features were added in v3.0. Thank you for the effort :)

**Pull request closed without merging**
